config/routes.rb
Rtsns::Application.routes.draw do

  get "dashboard/index"
  resources :groups do
    member do
      get :join
      get :leave
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  namespace :admin do
    root :to => "dashboard#index"
    resources :groups
  end

  root :to => 'home#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :creator, :class_name => 'User', :foreign_key => :user_id
  has_many :member_groupships, :dependent => :destroy
  has_many :members, :through => :member_groupships, :class_name => 'User', :source => :user
  
  mount_uploader :picture, GroupUploader
  
  validates_presence_of :title
  validates_uniqueness_of :title
  validates_presence_of :introduction
  
  attr_accessor :accessible
  
  before_save :update_members
  
  def update_members
    self.members_count = self.members.count
  end

  private
    def mass_assignment_authorizer(role = :default)
      if accessible == :all
        self.class.protected_attributes
      else
        super + (accessible || [])
      end
    end

end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::ApplicationController
  def index
    @search = Group.search(params[:search])
    @groups = @search.page(params[:page]).per(8).order('created_at DESC')

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @groups }
    end
  end

  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @group }
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def create
    @group = current_user.groups.new(params[:group])
    @group.verified = params[:group][:verified]
    @group.allowadduser = params[:group][:allowadduser]

    respond_to do |format|
      if @group.save
        format.html { redirect_to admin_groups_url, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @admin_group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @group = Group.find(params[:id])
    @group.accessible = :all if current_user.admin?

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to admin_groups_url, notice: 'Group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to admin_groups_url }
      format.json { head :ok }
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.page(params[:page]).per(20).order("members_count DESC")
    @newest_groups = Group.limit(10).order("created_at DESC")

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @groups }
    end
  end

  def show
    @group = Group.find(params[:id])
    @newest_users = @group.members.limit(8)

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :ok }
    end
  end
  
  def join
    @group = Group.find(params[:id])
    respond_to do |format|
      format.html do
        current_user.become_member_of(@group)
        redirect_to @group
      end
      format.js
    end
  end
  
  def leave
    @group = Group.find(params[:id])
    current_user.leave(@group)
    redirect_to @group
  end
  
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= simple_form_for(@group) do |f|
  = f.error_notification

  .inputs

  .actions
    = f.button :submit

app/views/groups/_group.html.haml
.group
  .group-img
    = link_to image_tag(group.picture_url(:s48)), group
    - if !group.verified
      %span.label 审核中
    - elsif !group.allowadduser
      %span.label 禁止加入
    - else
      = link_to "+加入", join_group_path(group), :class => "label success", :remote => true
  .group-desc
    %p
      = link_to group.title, group
      = "(#{group.members_count})"
      %br
      = truncate group.introduction, :length => 39,  :omission => "..."

app/views/groups/edit.html.haml
%h1 Editing group

= render 'form'

= link_to 'Show', @group
\|
= link_to 'Back', groups_path

app/views/groups/index.html.haml
- if user_signed_in?
  %ul.tabs
    %li{:class => ("active" if action_name == "index")}= link_to "全部小组", groups_path
- else
  %h5 全部小组

.groups.clearfix
  = render @groups
= paginate @groups

- content_for :sidebar do
  - if user_signed_in?
    %p= link_to "创建小组", new_group_path
  %h5 热门帖子
  %h5 新成立的小组
  - @newest_groups.each do |group|
    %p
      = image_tag group.picture_url(:s16)
      = link_to group.title, group
      = "(#{group.members_count})"
      

app/views/groups/join.js.erb
$('#notice-message').remove();
<% if @group and user_signed_in? %>
  <% if current_user.is_member_of?(@group) %>
	dialog_message("你已经加入该小组，请不要再次加入^_^");
  <% else %>
    <% if current_user.is_creator_of?(@group) %>
      dialog_message("你是小组的创建者^_^");
    <% else %>
      <% current_user.become_member_of(@group) %>
    	dialog_message("加入小组成功^_^");
    	setTimeout(function(){location.reload()}, 2000);
    <% end %>
  <% end %>
<% else %>
  dialog_message('你还没有登录^_^，<%= link_to "登录", new_user_session_path %>或者<%= link_to "注册", new_user_registration_path %>');
<% end %>

app/views/groups/new.html.haml
%h1 New group

= render 'form'

= link_to 'Back', groups_path

app/views/groups/show.html.haml
%h3= @group.title
.infobox.clearfix
  = image_tag @group.picture_url(:s48)
  .groupdesc
    %p
      = "创建于#{@group.created_at.strftime("%Y-%m-%d")}"
      &nbsp;&nbsp;组长
      = link_to @group.creator.name, "#"
    - if !@group.verified
      %p= "#{@group.title}小组正在审核中"
    - else
      %p= @group.introduction
      - if user_signed_in?
        - if current_user.is_member_of?(@group) and @group.allowadduser
          %h6
            我是这个小组的成员
            = link_to "退出小组", leave_group_path(@group)
        - elsif @group.creator == current_user
          %h6 你是这个小组的管理员
        - elsif !@group.allowadduser
          %h6 本小组禁止加入
        - else
          = link_to "加入小组", join_group_path(@group), :class => "btn success pull-right"
      - elsif !@group.allowadduser  
        %h6 本小组禁止加入
      - else
        = link_to "加入小组", join_group_path(@group), :class => "btn success pull-right"

-if @group.verified
  = link_to "发布帖子", "#", :class => "btn success"

.labels
  = link_to "全部", "#", :class => "label success"