config/routes.rb
Rtsns::Application.routes.draw do

  get "dashboard/index"
  resources :groups do
    member do
      get :join
      get :leave
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  namespace :admin do
    root :to => "dashboard#index"
    resources :groups
  end

  root :to => 'home#index'

end

app/views/shared/_admin_sidebar.html.haml
<h5>操作菜单</h5>
%ul
  %li= link_to "小组管理", admin_groups_path

app/views/shared/_error_message.html.haml
.alert-message.block-message.error
  %a.close{:href => "#"} ×
  = message

app/views/shared/_flash_message.html.haml
- if not flash[:notice].blank?
  .alert-message.info
    %a.close{:href => "#"} ×
    %p= flash[:notice]

- if not flash[:error].blank?
  .alert-message.error
    %a.close{:href => "#"} ×
    %p= flash[:error]

app/views/shared/_footer.html.haml
.footer
  .container
    %p
      2012 &copy; Steven Wang

app/views/shared/_topbar.html.haml
.topbar-wrapper
  .topbar
    .topbar-inner
      .container
        %h3= link_to "RTSNS", root_path
        %ul.nav
          %li{:class => "#{ 'active' if controller_name == 'groups'}"}= link_to "小组", groups_path
        %ul.nav.secondary-nav
          - if user_signed_in?
            %li= image_tag current_user.avatar_url(:s32), :style => "margin-top:3px;"
            %li.dropdown
              = link_to current_user.name, "#", :class => "dropdown-toggle"
              %ul.dropdown-menu
                %li= link_to "帐号设置", edit_user_registration_path
                - if current_user.admin?
                  %li= link_to "后台控制板", admin_root_path
                %li= link_to "退出", destroy_user_session_path, :method => :delete
          - else
            %li= link_to "注册", new_user_registration_path
            %li= link_to "登录", new_user_session_path