config/routes.rb
Rtsns::Application.routes.draw do

  get "dashboard/index"
  resources :groups do
    member do
      get :join
      get :leave
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  namespace :admin do
    root :to => "dashboard#index"
    resources :groups
  end

  root :to => 'home#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :creator, :class_name => 'User', :foreign_key => :user_id
  has_many :member_groupships, :dependent => :destroy
  has_many :members, :through => :member_groupships, :class_name => 'User', :source => :user
  
  mount_uploader :picture, GroupUploader
  
  validates_presence_of :title
  validates_uniqueness_of :title
  validates_presence_of :introduction
  
  attr_accessor :accessible
  
  before_save :update_members
  
  def update_members
    self.members_count = self.members.count
  end

  private
    def mass_assignment_authorizer(role = :default)
      if accessible == :all
        self.class.protected_attributes
      else
        super + (accessible || [])
      end
    end

end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::ApplicationController
  def index
    @search = Group.search(params[:search])
    @groups = @search.page(params[:page]).per(8).order('created_at DESC')

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @groups }
    end
  end

  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @group }
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def create
    @group = current_user.groups.new(params[:group])
    @group.verified = params[:group][:verified]
    @group.allowadduser = params[:group][:allowadduser]

    respond_to do |format|
      if @group.save
        format.html { redirect_to admin_groups_url, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @admin_group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @group = Group.find(params[:id])
    @group.accessible = :all if current_user.admin?

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to admin_groups_url, notice: 'Group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to admin_groups_url }
      format.json { head :ok }
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.page(params[:page]).per(20).order("members_count DESC")
    @newest_groups = Group.limit(10).order("created_at DESC")

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @groups }
    end
  end

  def show
    @group = Group.find(params[:id])
    @newest_users = @group.members.limit(8)

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :ok }
    end
  end
  
  def join
    @group = Group.find(params[:id])
    respond_to do |format|
      format.html do
        current_user.become_member_of(@group)
        redirect_to @group
      end
      format.js
    end
  end
  
  def leave
    @group = Group.find(params[:id])
    current_user.leave(@group)
    redirect_to @group
  end
  
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/admin/groups/_form.html.haml
= simple_form_for [:admin, @group], :wrapper => :inline, :html => {:multipart => true} do |f|
  = rtsns_error_messages(@group)
  = f.input :title, :input_html => {:class => "span7"}
  = f.input :introduction, :as => :text, :input_html => {:rows => 8, :class => "span7"}
  = f.input :picture, :label => false do
    = image_tag @group.picture_url(:s48)
  = f.input :picture, :hint => "最好48x48尺寸"
  = f.input :verified do
    .collection_container= f.collection_radio :verified, [[true, '通过'] ,[false, '不通过']], :first, :last
  = f.input :allowadduser do
    .collection_container= f.collection_radio :allowadduser, [[true, '允许'] ,[false, '不允许']], :first, :last
  .actions
    = f.submit :class => "btn primary"
    = link_to "返回", admin_groups_path, :class => "btn"

app/views/admin/groups/edit.html.haml
%h1 编辑小组

= render 'form'

app/views/admin/groups/index.html.haml
%h2
  小组列表
  = link_to "添加小组", new_admin_group_path, :class => "btn success pull-right"

= simple_form_for @search, :url => admin_groups_path, :method => 'get', :id => "admin_group_search_form" do |f|
  = f.input :title_contains, :label => false, :input_html => { :class => "span7" }
  
%table
  %thead
    %tr
      %th 名称
      %th 审核状态
      %th 允许加入
      %th 成员数量
      %th 操作
  %tbody
    - @groups.each do |group|
      %tr
        %td
          = image_tag group.picture_url(:s16)
          = group.title
        %td
          - if group.verified
            %span.label.success 通过
          - else
            %span.label 审核中
        %td
          - if group.allowadduser
            %span.label.success yes
          - else
            %span.label no
        %td= group.members_count
        %td
          = link_to "编辑", edit_admin_group_path(group), :class => "btn"
          = link_to "删除", admin_group_path(group), :class => "btn", :method => :delete, :confirm => "你确定?"

= paginate @groups

app/views/admin/groups/new.html.haml
%h2 创建小组

= render 'form'